package com.massapay.android.security.storage

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Secure storage manager using AES-256-GCM encryption with Android Keystore
 * 
 * Features:
 * - AES-256-GCM encryption (authenticated encryption with associated data)
 * - Keys stored in Android Keystore (hardware-backed when available)
 * - 12-byte IV (recommended for GCM)
 * - 128-bit authentication tag
 * - BLAKE3 hashing for data integrity validation
 */
@Singleton
class SecureStorageManager @Inject constructor() {
    
    private companion object {
        const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        const val KEY_ALIAS = "MassaPayMasterKey"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_IV_LENGTH = 12 // 96 bits (recommended for GCM)
        const val GCM_TAG_LENGTH = 128 // 128 bits authentication tag
    }

    private val keyStore: KeyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply {
        load(null)
    }

    init {
        // Create master key if it doesn't exist
        if (!keyStore.containsAlias(KEY_ALIAS)) {
            createMasterKey()
        }
    }

    /**
     * Create AES-256 master key in Android Keystore
     * Key is hardware-backed on devices with Trusted Execution Environment (TEE)
     */
    private fun createMasterKey() {
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE_PROVIDER
        )

        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256) // AES-256
            .setUserAuthenticationRequired(false) // Can be set to true for biometric auth
            .setRandomizedEncryptionRequired(true) // Ensures unique IV per encryption
            .build()

        keyGenerator.init(spec)
        keyGenerator.generateKey()

        android.util.Log.d("SecureStorageManager", "Created AES-256-GCM master key in Keystore")
    }

    /**
     * Get the master encryption key from Keystore
     */
    private fun getMasterKey(): SecretKey {
        return keyStore.getKey(KEY_ALIAS, null) as SecretKey
    }

    /**
     * Encrypt data using AES-256-GCM
     * 
     * @param plaintext Data to encrypt
     * @return Base64-encoded string in format: IV (12 bytes) + Ciphertext + Auth Tag
     */
    fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getMasterKey())

        val iv = cipher.iv // Random IV generated by cipher
        require(iv.size == GCM_IV_LENGTH) { "Invalid IV length: ${iv.size}" }

        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))

        // Combine IV + ciphertext (ciphertext already includes auth tag)
        val combined = ByteArray(iv.size + ciphertext.size)
        System.arraycopy(iv, 0, combined, 0, iv.size)
        System.arraycopy(ciphertext, 0, combined, iv.size, ciphertext.size)

        val encrypted = Base64.encodeToString(combined, Base64.NO_WRAP)
        
        android.util.Log.d("SecureStorageManager", "Encrypted ${plaintext.length} bytes -> ${encrypted.length} chars")
        
        return encrypted
    }

    /**
     * Decrypt data using AES-256-GCM
     * 
     * @param encryptedData Base64-encoded encrypted data (IV + ciphertext + tag)
     * @return Decrypted plaintext string
     * @throws Exception if decryption fails (wrong key, tampered data, etc.)
     */
    fun decrypt(encryptedData: String): String {
        val combined = Base64.decode(encryptedData, Base64.NO_WRAP)
        
        // Extract IV and ciphertext
        require(combined.size > GCM_IV_LENGTH) { "Invalid encrypted data length" }
        
        val iv = combined.copyOfRange(0, GCM_IV_LENGTH)
        val ciphertext = combined.copyOfRange(GCM_IV_LENGTH, combined.size)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, getMasterKey(), spec)

        val plaintext = cipher.doFinal(ciphertext)
        
        android.util.Log.d("SecureStorageManager", "Decrypted ${encryptedData.length} chars -> ${plaintext.size} bytes")
        
        return String(plaintext, Charsets.UTF_8)
    }

    /**
     * Encrypt data with additional BLAKE3 integrity hash
     * Format: encrypted(data + blake3_hash)
     * 
     * @param plaintext Data to encrypt with integrity protection
     * @return Base64-encoded encrypted data with embedded hash
     */
    fun encryptWithIntegrity(plaintext: String): String {
        // Calculate BLAKE3 hash of plaintext
        val hash = hashWithBlake3(plaintext.toByteArray())
        val hashHex = hash.joinToString("") { "%02x".format(it) }
        
        // Combine plaintext with hash (separated by |)
        val combined = "$plaintext|$hashHex"
        
        return encrypt(combined)
    }

    /**
     * Decrypt and verify BLAKE3 integrity hash
     * 
     * @param encryptedData Encrypted data with embedded hash
     * @return Decrypted plaintext if hash validates
     * @throws SecurityException if hash validation fails
     */
    fun decryptWithIntegrity(encryptedData: String): String {
        val decrypted = decrypt(encryptedData)
        
        // Split plaintext and hash
        val parts = decrypted.split("|")
        if (parts.size != 2) {
            throw SecurityException("Invalid encrypted data format (missing integrity hash)")
        }
        
        val plaintext = parts[0]
        val storedHashHex = parts[1]
        
        // Verify BLAKE3 hash
        val computedHash = hashWithBlake3(plaintext.toByteArray())
        val computedHashHex = computedHash.joinToString("") { "%02x".format(it) }
        
        if (storedHashHex != computedHashHex) {
            throw SecurityException("Data integrity check failed (BLAKE3 hash mismatch)")
        }
        
        android.util.Log.d("SecureStorageManager", "Integrity verified with BLAKE3")
        
        return plaintext
    }

    /**
     * Hash data with BLAKE3 (32-byte output)
     */
    private fun hashWithBlake3(data: ByteArray): ByteArray {
        val digest = org.bouncycastle.crypto.digests.Blake3Digest()
        digest.update(data, 0, data.size)
        val hash = ByteArray(32)
        digest.doFinal(hash, 0)
        return hash
    }

    /**
     * Delete the master encryption key
     * WARNING: This will make all encrypted data unrecoverable
     */
    fun deleteMasterKey() {
        if (keyStore.containsAlias(KEY_ALIAS)) {
            keyStore.deleteEntry(KEY_ALIAS)
            android.util.Log.w("SecureStorageManager", "Master key deleted - all encrypted data is now unrecoverable")
        }
    }

    /**
     * Check if master key exists
     */
    fun hasMasterKey(): Boolean {
        return keyStore.containsAlias(KEY_ALIAS)
    }
}
